language: node_js
node_js: 
  - "8.4"
  - "stable"

script: npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: dist
  target-branch: build
